### PR TITLE
fix popover width so that it becomes equal to table width

### PR DESCRIPTION
**Pull request by siddhi-244**
## Fixed the popover width! Screenshot below shows the output !
Screenshot (432)

- I am a outreachy participant !

## Implementation 
- Used  Paperprops to style the popover !

Resolves - #225

### CODE REVIEW

**Comment by cybraia** [comment]
Hi, I tried the same thing. Doesn't seem to work for me. What did you do differently?

**Comment by siddhi-244** [comment]
@kimberlythegeek please review this !

**Comment by siddhi-244** [comment]
hey @Carla-Moz , could you please review the pr and merge it? Also can i get your username on element app as i have some questions regarding other issue !

**Review by kimberlythegeek — CHANGES_REQUESTED** [review]
please use relative sizing or media queries instead of a static width

**Comment by siddhi-244** [comment]
> Hi! Thank you for your contribution. In general, we prefer to avoid hard-coded widths or other dimensions.
> 
> Also, this solution does not appear to work on all screens: image

The website itself is not responsive on all the screens ! And I didn't find a 

> please use relative sizing or media queries instead of a static width

Cool !

**Comment by siddhi-244** [comment]
@kimberlythegeek ?

**Comment by kimberlythegeek** [comment]
looks good, thanks!

**Review by kimberlythegeek — APPROVED** [review]

**Comment by siddhi-244** [comment]
> looks good, thanks!

can i record this contribution on the outreachy portal ?

**Pull request merged**
