### PR TITLE
add framework selection dropdown

### PR DESCRIPTION
**Pull request by kimberlythegeek**

### CODE REVIEW

**Comment by kimberlythegeek** [comment]
Coverage report: https://app.codecov.io/github/mozilla/perfcompare/commit/565eb1b741c9327654e5a3015635b5857ef792ed

**Review by beatrice-acasandrei — COMMENTED** [review]
@kimberlythegeek If you select a framework with results and then select a framework that doesn't have data, the results from the previous choice are still displayed along with the error "Error: No results found".

**Comment by kimberlythegeek** [comment]
> 

thanks for catching this! I've updated the `setFramework` reducer to clear results when called. I also moved the framework dropdown outside of the compare results table, because if the initial framework (talos) had no results, a user would not be able to switch to another framework.

**Comment by kimberlythegeek** [comment]
I noticed that the dropdown will display even while the results are loading, so I'll need to address this

**Comment by kimberlythegeek** [comment]
coverage report: https://app.codecov.io/github/mozilla/perfcompare/commit/8b617d94d0e77f02212ce6843e209c1ea01cb047

**Comment by beatrice-acasandrei** [comment]
@kimberlythegeek Possible bug: If there's no data for a particular framework then the dropdown (for the frameworks) should still be displayed.

**Comment by kimberlythegeek** [comment]
@beatrice-acasandrei I apologize--I thought I had resolved the issue but evidently I did not :facepalm:

**Pull request closed without merging**
