### PR TITLE
Fix: Improve UX design for the search result list #394

### PR DESCRIPTION
**Pull request by Hajihbola**
Improve UX design for the search result list #394 to improve scroll user experience

### CODE REVIEW

**Comment by Carla-Moz** [comment]
Could you please add a screenshot to your PR showing it fixes the issue? Thanks!

**Comment by Hajihbola** [comment]
> Could you please add a screenshot to your PR showing it fixes the issue? Thanks!

Screenshot (1)

**Comment by Hajihbola** [comment]
I'm open to make any adjustment where necessary please.
Thanks.

**Comment by Hajihbola** [comment]
I will have the screenshot taken please when I have my laptop charged in few hours time.

**Comment by Hajihbola** [comment]
> Could you please add a screenshot to your PR showing it fixes the issue? Thanks!

Screenshot (11)
Screenshot (13)

**Comment by Hajihbola** [comment]
@kimberlythegeek  @Carla-Moz
What is the next thing I'm meant to do in order to meet up with the final application deadline please?

**Pull request closed without merging**
