### PR TITLE
Fixed Confidence tooltip breaking UI and added some SVG loader to webpack to solve the import of SVGs  #258

### LINKED ISSUE #258: Confidence tooltip breaks UI
when there is a result that has unknown confidence, the alignment of the cell is disrupted, and after several of these in the same table, the difference becomes very apparent:

image

one suggestion would be to use SVG images directly and wrapping them in a `Tooltip` component, rather than wrapping the Table Cell, which seems to be where the issue arises.

When adding these icons originally, I encountered issues with using SVG images in typescript, which is why the background image approach was taken. Since ejecting and switching to webpack, this may no longer be an issue

### PR DESCRIPTION
**Pull request by Bukolab99**
Fixes #258 , My changes was to ensure that the TableCell component doesn't break the UI if result.confidence_text is null and to change the style for the missing-confidence-button class so that the IconButton component is centered vertically inside the TableCell component. To achieve this, the following steps were taken:

To prevent the TableCell component from breaking the UI, I  use a conditional statement to check if the result.confidence_text is null. If it is null, we can set a default value to be displayed in the TableCell component.

To center the IconButton component vertically inside the TableCell component, we can add the padding-top: 0px style property to the missing-confidence-button class.

Once the changes are made, the snapshot files should update to reflect the new UI.
And also fixed @NikolaDojic's follow up [comment ](https://github.com/mozilla/perfcompare/issues/258#issuecomment-1403332822)
With the changes I made, you should now be able to import and use SVGs in your React codebase with the help of the added SVGR loader. @kimberlythegeek Please review.

### CODE REVIEW

**Comment by NikolaDojic** [comment]
I don't think this will resolve the #258 issue. Fixing the broken layout is not part of the changes.
However, it potentially resolves https://github.com/mozilla/perfcompare/issues/125.

**Comment by Bukolab99** [comment]
> 

So I need to fix the broken layout to completely resolve issue #258 ?

**Comment by NikolaDojic** [comment]
> > 
> 
> So I need to fix the broken layout to completely resolve issue #258 ?
I would assume so since the title of the #258 issue is _Confidence tooltip breaks UI_

**Comment by anna-kulyk** [comment]
@NikolaDojic #125 was assigned to me recently. And it says to install file-loader. Do I have to stop working on it? Does svgr is a better choice?

**Comment by Bukolab99** [comment]
> choice?

I think any applicant can work on any issue. It’s just going to be a matter of comparison.

**Comment by NikolaDojic** [comment]
Just to be clear guys, I'm not associated with Mozilla in any way other than personal fondness, and some occasional code contribution.
All I can do is give my opinion and/or advice, but it is important that you understand where is this coming from.

That being said I would personally go for the implementation that is similar to the one already in the codebase. In this case, that means going with `file-loader`, based on the description from the tickets. 

Even if this kind of PR does not end up in the code base it is not a big waste ;)
In addition, if your only goal is to demonstrate your skill, then it does not matter if it ends up in the master branch.

**Pull request closed without merging**
