### PR TITLE
Improved accessibility

### PR DESCRIPTION
**Pull request by sabbCodes**
Worked on the accessibility of the compare revisions button by adding an aria-label tag.

#352

### CODE REVIEW

**Comment by jrbenny35** [comment]
Hi @sabbCodes, which issue does this PR pertain to?

**Comment by sabbCodes** [comment]
> Hi @sabbCodes, which issue does this PR pertain to?

I noticed there's need to improve the accessibility on the compare button.
So I fixed it. Forgot to open an issue for it.

**Review by kimberlythegeek — APPROVED** [review]
looks good to me, thank you for your contribution!

**Comment by sabbCodes** [comment]
> @sabbCodes In the future, please provide more specific information both in the title of your PRs and issues, and in the descriptions.
> 
> For example: "added aria-label to compare button to improve accessibility" as a title. The description could be something like "I noticed the compare button did not have an aria-label. Added a label to improve accessibility."

I'll take note of that and make corrections next time

**Pull request closed without merging**
