### PR TITLE
Single run expandable row

### PR DESCRIPTION
**Pull request by beatrice-acasandrei**

### CODE REVIEW

**Comment by Carla-Moz** [comment]
Screenshot 2023-05-18 at 11 05 29

Could you please change the icon to an **up arrow** when expanded?

**Comment by Carla-Moz** [comment]
@beatrice-acasandrei Also, I noticed that you disabled the download and retrigger buttons. For now, that's not necessary because we will hide them for the All-Hands demo since they are not part of the MVP. Until then, they can stay visible and enabled for UI building purposes for when I do the the QA on styles.

**Comment by Carla-Moz** [comment]
@beatrice-acasandrei, I noticed the dark mode toggle is missing. Do I need to redo the header for the results page?

**Review by Carla-Moz — CHANGES_REQUESTED** [review]
Looks great! I added some suggestions and comments below.

**Comment by beatrice-acasandrei** [comment]
> @beatrice-acasandrei Also, I noticed that you disabled the download and retrigger buttons. For now, that's not necessary because we will hide them for the All-Hands demo since they are not part of the MVP. Until then, they can stay visible and enabled for UI building purposes for when I do the the QA on styles.

@Carla-Moz This was part of Andra's previous PR, but I can change that in my PR if needed.

**Review by esanuandra — APPROVED** [review]
looks good

**Pull request merged**
