### PR TITLE
sorted confidence level in decending order

### PR DESCRIPTION
**Pull request by mercybassey**
This PR displays results in descending order based on confidence levels, from high to medium and then to low.

Issue: #766

### CODE REVIEW

**Comment by hibaa03** [comment]
Hi, check the README doc to check and run the validators and tests if you're facing issues with it

**Comment by mercybassey** [comment]
> Hi, check the README doc to check and run the validators and tests if you're facing issues with it

Thank you @hibaa03. I am currently working on it.

**Comment by mercybassey** [comment]
@Carla-Moz my tests are still failing, I'd really appreciate your help.

**Comment by julienw** [comment]
I believe that the test issues come from the fact that now that the "high" confidence value is selected by default, this filters out the results. If you look at the test data we're using in our tests (src/__tests__/utils/fixtures.ts), you'll see that some of the results are using `confidence: 'High'`, however in some tests we use only the first result (because it makes the test faster) that has `confidence: 'Low'`. Without looking closer, I think this is the issue.

I think the easiest fix would be to change the first result in `testCompareData` to have `confidence: 'High'` so that it would be displayed in these tests.
Another fix would be to manually select the other options in the filter, in each of these tests, but this seems more work.

**Review by julienw — CHANGES_REQUESTED** [review]
The initial issue incorrectly mentioned to _sort_ the values, but we really just want to _filter_ them. Sorting is too complex with our current structure. Thanks for your understanding.
Can you please make these changes?

**Comment by mercybassey** [comment]
> The initial issue incorrectly mentioned to _sort_ the values, but we really just want to _filter_ them. Sorting is too complex with our current structure. Thanks for your understanding. Can you please make these changes?

Sure

**Comment by mercybassey** [comment]
@julienw it seems just changing the first result in `testCompareData` to have confidence: 'High' didn't resolve the issue.

**Comment by mercybassey** [comment]
> @julienw it seems just changing the first result in `testCompareData` to have confidence: 'High' didn't resolve the issue.

This is my result locally. 
perf

**Comment by julienw** [comment]
Hey @mercybassey, I'm gonna close this PR now, because some recent changes in our codebase made this change less useful and we'd like to gather feedback before doing it. But thanks again for your work!

**Pull request closed without merging**
