### PR TITLE
Resolved accessibility issues in `SearchResultsListItem` component

### LINKED ISSUE #302: Missing labels in search results checkboxes
The checkboxes in the SearchResultsListItem components are missing labels and this causes accessibility tests to fail

### PR DESCRIPTION
**Pull request by taofeeqhamzat**
# Summary
Some accessibility standards violations in the `SearchResultsList` component cause [tests](https://app.circleci.com/pipelines/github/mozilla/perfcompare/1103/workflows/8aaaeeb7-a7d5-422a-90fa-29257fe7c1e4/jobs/1107/parallel-runs/0/steps/0-107) to fail. These violations include:

1. Missing aria-label in certain `input`(checkbox) elements,
2. `li` element not being a direct descendant of `ul`, having other elements in-between,
3. and an interactive element(checkbox) nested within another interactive element(button).

## Before:
1. The content of the unlabeled checkboxes (rendered by [`Checkbox`](https://mui.com/material-ui/react-checkbox/) in `SearchResultsListItem` component) were unidentifiable to assistive technologies like screen readers and users who rely on them.
2. The structure of the list of revisions in the search results list was ambiguous to assistive technologies like screen readers and they may not be able to announce to users that they are reading a list.
3. Focusable elements (e.g checkboxes) with interactive elements (e.g buttons) as parents are not announced by screen readers and some users may face difficulty using them. 

## Changes: 
This pull request:
- Passes 'aria-label' attributes, in the format of "(commit-message) by (author)", down in a prop to the checkboxes, as recommended by the [MUI docs](https://mui.com/material-ui/react-checkbox/). For violation 1.
- Reverses the nesting order of the [`ListItemButton`](https://mui.com/material-ui/api/list-item-button/) and [`ListItem`](https://mui.com/material-ui/api/list-item/) in `SearchResultsListItem` component. For violation 2.
- Changes the role attribute of [`ListItemButton`](https://mui.com/material-ui/api/list-item-button/) which renders a `div` element from 'button' to ['group'](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/group_role). For violation 3.
- Updates snapshot files.
- Closes #302.

### CODE REVIEW

**Review by kimberlythegeek — APPROVED** [review]
Awesome work! thank you so much, I appreciate the updates to the readme, and your detailed information on the changes you made :blush:

**Comment by kimberlythegeek** [comment]
I will be changing the base branch to `beta`, our team has decided to merge all contributor patches to this branch, and patches by team members to `staging`

**Comment by taofeeqhamzat** [comment]
Thank you for making my day with your thoughtful feedback @kimberlythegeek 😄

**Comment by taofeeqhamzat** [comment]
I have now resolved the merge conflicts that came with changing the base branch. My branch is now synced with and ready to be merged to the new base branch.

**Review by kimberlythegeek — APPROVED** [review]
looks good--thank you!

**Comment by kimberlythegeek** [comment]
> I have now resolved the merge conflicts that came with changing the base branch. My branch is now synced with and ready to be merged to the new base branch, beta.

apologies for the confusion in branches :sweat_smile:

**Pull request merged**
