### PR TITLE
FXP-2469 [PerfCompare] Apply button from warning message is not clickable

### PR DESCRIPTION
**Pull request by esanuandra**

### CODE REVIEW

**Review by Carla-Moz — COMMENTED** [review]
Have you tried updating your snapshots? Running `npm test -- -u` All the tests pass once I updated the snapshots.

**Comment by esanuandra** [comment]
> Have you tried updating your snapshots? Running `npm test -- -u` All the tests pass once I updated the snapshots.

I ran the command and the snapshots were alright. I'm having issues on adding coverage for `CompareResultsTableHead.tsx#L145-L146`

**Comment by Carla-Moz** [comment]
> > Have you tried updating your snapshots? Running `npm test -- -u` All the tests pass once I updated the snapshots.
> 
> I ran the command and the snapshots were alright. I'm having issues on adding coverage for `CompareResultsTableHead.tsx#L145-L146`

Oh, so sorry, for some reason I thought you had already written the test. @kimberlythegeek, could you help Andra, here. I'm deep in finishing up the theme work/wrapping up task #0.

**Review by kimberlythegeek — APPROVED** [review]
@esanuandra looks good to me--if you like you can create separate patch for test coverage, I'll look into it by the end of this week. React tests can be tricky, hah

**Pull request merged**
