### PR TITLE
revision link open new tab #280

### PR DESCRIPTION
**Pull request by NikolaDojic**
closes:
revision link in selected revisions should open treeherder in new tab #280

### CODE REVIEW

**Comment by beatrice-acasandrei** [comment]
@NikolaDojic please rebase with latest staging and update your snapshots (`npm run test -- -u`).

**Comment by NikolaDojic** [comment]
@beatrice-acasandrei  
unfortunately, tests are failing after I've done that.

what I did is:

position myself to my local staging branch

`git fetch upstream`, 
`reset --hard upstream/staging`

made changes to `SelectedRevisionsTableRow`

`npm run test -- -u`
`git add -A`
`git commit -m "[some comment]"`
`git push`

I've tried this with node versions `18.x`, and `16.13.x`, the result was unchanged.

Do you think it would make sense to change the README file to use the command that you mentioned
`npm run test -- -u` instead of `jest --updateSnapshot`?
I find that the letter command is a bit ambiguous since it won't work out of the box in most cases, and is left for users to decide how they want to make it run.

**Comment by NikolaDojic** [comment]
@beatrice-acasandrei , 
jsut FYI
I think I found the source of this issue. 
There was a mismatch in @swc/core libraries. 
in the package.json it was listed as both:  dependency and dev-dependency, with different versions.
I've removed it from dependencies(since it is not used in the src folder), 
re-installed node modules, and cirecleci tests started to pass again

**Comment by NikolaDojic** [comment]
@beatrice-acasandrei I don't have the right permission to add labels to the PRs, but you can consider this ready for review.
on a somewhat related note, I tried joining the slack channel, but it is no longer available.

**Review by kimberlythegeek — APPROVED** [review]
looks good to me, thanks! I'm looking in to the best way to allow outside contributors to add labels.

**Review by esanuandra — APPROVED** [review]

**Pull request merged**
